#!/bin/bash

#default editor
export edit=vim

#gitdir
export gitdir=~/git

#utils
export utilsdir=$gitdir/utils
export scriptsdir=$utilsdir/scripts

#bash
export bashrc=~/.bashrc
export aliases=~/.aliases
export variables=~/.variables
export session_variables=~/.session_variables

#vim
export vimrc=~/.vimrc
export vimdir=~/.vim

#path
export PATH="$HOME/.local/bin:$PATH"

#gdm
export gdm_home=/var/lib/gdm
